### ISSUE TITLE
JSON dependency error in 2.4.9

### ISSUE THREAD

**Issue by robertstinnett** [express42/zabbixapi#70]
We are getting an error when we attempt to go to any version of chef-client above 12.15.9 when using the 2.4.9 branch.  It appears there is a JSON change in chef-client that is conflicting with the JSON here.  We are seeing the following:

Gem::ConflictError: carfax_zabbix_api_host[ip-172-26-210-38.w.cdc.cfx] (carfax_zabbix_api::default line 47) had an error: Gem::ConflictError: Unable to activate zabbixapi-2.4.9, because json-2.0.2 conflicts with json (>= 1.6.0, ~> 1.6)

I see talk about JSON2 support, but it appears that is only for the 3.0.x branches - is that correct?

**Comment by jrbeilke** [comment]
Yep, support for json 2.0 was added in zabbixapi 3.x along with dropping support for older versions of Ruby (ie. 1.9) - https://github.com/express42/zabbixapi/pull/65

**Comment by robertstinnett** [comment]
The 3.0 gem doesn't work with Zabbix 2.4.x systems, correct?  Sorry, the README is a bit confusing.

**Comment by jrbeilke** [comment]
Hmm, if you need json 2.0 support then you'll need to use the 3.0 gem. Technically the 3.0 gem should work with the Zabbix 2.4 API, but we no longer run the unit tests against it.

The only issue that I'm aware of would be the change to support Zabbix 3.2 which uses the new maintenance mode flag on actions - https://github.com/express42/zabbixapi/pull/55

Instead of using :maintenance_mode => '1' with your actions you would need to use the older syntax of checking Maintenance status = not in “maintenance” with an action filter condition (conditiontype # 16 for maintenance status).
